[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
digital_signatures_contract = "4hJvxjMukCmenaWiPrMSsLZBQJDB8Tpk8c79dsGna4UT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
